include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI support for Netmon
LUCI_DEPENDS:=+luci-base +netmon-core
LUCI_PKGARCH:=all

PKG_NAME:=luci-app-netmon
PKG_VERSION:=1.2.1
PKG_RELEASE:=1
PKG_MAINTAINER:=MYAN

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
